#ifndef QXTIMELINEEDITOR_GLOBAL_H
#define QXTIMELINEEDITOR_GLOBAL_H

#include <QtGlobal>

#if defined(QXTIMELINEEDITOR_LIBRARY)
#  define QXTIMELINEEDITOR_EXPORT Q_DECL_EXPORT
#else
#  define QXTIMELINEEDITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // QXTIMELINEEDITOR_GLOBAL_H